Add vscode snippets for procon

diff --git a/bin/refresh-snippet b/bin/refresh-snippet
--- a/bin/refresh-snippet
+++ b/bin/refresh-snippet
@@ -4,16 +4,27 @@ set -e
 
 GHQ_ROOT=$(ghq root)
 LIBPROCON_PATH=$(ghq list | grep libprocon)
-DEST_DIR=${XDG_CONFIG_HOME}/coc/ultisnips
+ULTISNIPS_DEST_DIR=${XDG_CONFIG_HOME}/coc/ultisnips
+VSCODE_DEST_DIR=${XDG_CONFIG_HOME}/vscode/snippets
 
-if [[ ! -d ${DEST_DIR} ]]; then
-  echo "The target directory does not exist: ${DEST_DIR}"
+if [[ ! -d ${ULTISNIPS_DEST_DIR} ]]; then
+  echo "The target directory for ultisnips does not exist: ${ULTISNIPS_DEST_DIR}"
+  echo "Abort."
+  exit 1
+fi
+
+if [[ ! -d ${VSCODE_DEST_DIR} ]]; then
+  echo "The target directory for vscode does not exist: ${VSCODE_DEST_DIR}"
   echo "Abort."
   exit 1
 fi
 
 cd ${GHQ_ROOT}/${LIBPROCON_PATH}
-cargo snippet -t ultisnips > "${DEST_DIR}/rust.snippets"
+
+# ultisnips
+cargo snippet -t ultisnips > "${ULTISNIPS_DEST_DIR}/rust.snippets"
+# vscode
+cargo snippet -t vscode > "${VSCODE_DEST_DIR}/libprocon.code-snippets"
 echo "Refreshing snippets have been done!"
 
 # Update cargo-atcoder.toml
